// --- Popular Google Fonts list ---
export const GOOGLE_FONTS = [
  'Inter',
  'Roboto',
  'Open Sans',
  'Lato',
  'Montserrat',
  'Poppins',
  'Raleway',
  'Nunito',
  'DM Sans',
  'Source Sans 3',
  'Oswald',
  'Playfair Display',
  'Merriweather',
  'PT Sans',
  'Noto Sans',
  'Ubuntu',
  'Rubik',
  'Work Sans',
  'Mulish',
  'Quicksand',
  'Barlow',
  'Manrope',
  'Outfit',
  'Plus Jakarta Sans',
  'Space Grotesk',
  'Sora',
  'Figtree',
  'Lexend',
  'Cabin',
  'Karla',
  'Libre Franklin',
  'Josefin Sans',
  'Archivo',
  'Red Hat Display',
  'Urbanist',
  'Albert Sans',
  'Geist',
  'Hind',
  'Titillium Web',
  'Fira Sans',
  'Exo 2',
  'Comfortaa',
  'Catamaran',
  'Jost',
  'Overpass',
  'Signika',
  'Encode Sans',
  'Asap',
  'Nanum Gothic',
  'IBM Plex Sans',
  'IBM Plex Mono',
  'JetBrains Mono',
  'Fira Code',
  'Source Code Pro',
  'Roboto Mono',
  'Space Mono',
  'Inconsolata',
  'Roboto Slab',
  'Noto Serif',
  'Libre Baskerville',
  'Lora',
  'PT Serif',
  'Crimson Text',
  'EB Garamond',
  'Cormorant Garamond',
  'Bitter',
  'Vollkorn',
  'Spectral',
  'DM Serif Display',
  'Fraunces',
  'Bebas Neue',
  'Anton',
  'Righteous',
  'Alfa Slab One',
  'Passion One',
  'Bungee',
  'Permanent Marker',
  'Pacifico',
  'Caveat',
  'Dancing Script',
  'Satisfy',
  'Great Vibes',
  'Sacramento',
  'Kalam',
  'Shadows Into Light',
  'Indie Flower',
  'Patrick Hand',
  'Amatic SC',
];

/** Build a Google Fonts CSS import URL for a list of font names */
export const buildGoogleFontsUrl = (fonts) => {
  const families = fonts.map(f => `family=${f.replace(/ /g, '+')}`).join('&');
  return `https://fonts.googleapis.com/css2?${families}&display=swap`;
};

/** Single font link tag for injection into iframe */
export const fontLinkTag = (fontName) =>
  `<link href="https://fonts.googleapis.com/css2?family=${fontName.replace(/ /g, '+')}&display=swap" rel="stylesheet">`;
