// To add a new template: use /admin/templates to generate the config line,
// then add it below and place the HTML file in public/templates/
export const TEMPLATES = [
  { id: 'propvision', name: 'PropVision AI', desc: 'Warm minimalist real estate', color: 'bg-stone-50', file: 'PropVision-AI.html' },
  { id: 'papaya', name: 'PaPaya Streaming', desc: 'Dark tech-forward dashboard', color: 'bg-black', file: 'abc.html' },
  { id: 'ventus', name: 'Ventus Financial OS', desc: 'Clean minimalist finance', color: 'bg-white', file: 'agency-portfolio.html' },
  { id: 'frame', name: 'Frame AI Product', desc: 'Sharp geometric design', color: 'bg-slate-900', file: 'ai-product.html' },
  { id: 'oblique', name: 'OBLIQUE Spatial', desc: 'Light minimal Linear aesthetic', color: 'bg-gray-100', file: 'architecture.html' },
  { id: 'aura-sonic', name: 'Aura Sonic', desc: 'Dark moody music architecture', color: 'bg-black', file: 'aura-sonic.html' },
  { id: 'aventra', name: 'Aventra Design', desc: 'Glass morphism with 3D', color: 'bg-white', file: 'aventra.html' },
  { id: 'canvas', name: 'Canvas SaaS', desc: 'Clean blue-accented builder', color: 'bg-white', file: 'canvas.html' },
  { id: 'designer-portfolio', name: 'Designer Portfolio', desc: 'Bold purple massive typography', color: 'bg-violet-600', file: 'designer-portfolio.html' },
  { id: 'finance-flow', name: 'FinanceFlow Banking', desc: 'Modern blue finance UI', color: 'bg-slate-50', file: 'finance-flow.html' },
  { id: 'finex-finance', name: 'Finex Finance', desc: 'Dark sleek finance platform', color: 'bg-slate-950', file: 'finex-finance.html' },
  { id: 'finex-gaming', name: 'Finex Gaming', desc: 'Neon black gaming infra', color: 'bg-black', file: 'finex-gaming.html' },
  { id: 'fluxer', name: 'Fluxer SaaS', desc: 'Dark minimalist canvas', color: 'bg-slate-950', file: 'fluxer-saas.html' },
  { id: 'obelisk', name: 'OBELISK Futuristic', desc: 'Cyberpunk infrared aesthetic', color: 'bg-red-950', file: 'futuristic.html' },
  { id: 'hardcore-fitness', name: 'Hardcore Fitness', desc: 'Aggressive red-accented fitness', color: 'bg-zinc-900', file: 'hadrcore-fitness.html' },
  { id: 'interstellar', name: 'Interstellar Logistics', desc: 'Dark space-themed logistics', color: 'bg-slate-950', file: 'interstellar-logistics.html' },
  { id: 'ledger', name: 'Ledger SaaS', desc: 'Slate finance platform', color: 'bg-slate-50', file: 'ledger-saas.html' },
  { id: 'ledgerly', name: 'Ledgerly AI Social', desc: 'Clean modern social growth', color: 'bg-white', file: 'ledgerly.html' },
  { id: 'luminal', name: 'Luminal Studio', desc: 'Dark with animated beams', color: 'bg-slate-950', file: 'luminal.html' },
  { id: 'luxury-interior', name: 'Luxury Interior', desc: 'Elegant bespoke interior', color: 'bg-stone-50', file: 'luxury-interior.html' },
  { id: 'mindful', name: 'Mindful Wellness', desc: 'Light zen meditation app', color: 'bg-white', file: 'mindful.html' },
  { id: 'lumen-photo', name: 'LUMEN Photography', desc: 'Dark portfolio with grid', color: 'bg-slate-950', file: 'photography-portfolio.html' },
  { id: 'xstudio', name: 'X.Studio Portfolio', desc: 'Dark blue-violet developer', color: 'bg-slate-950', file: 'portfolio-2.html' },
  { id: 'frontend-portfolio', name: 'Frontend Portfolio', desc: 'Ultra-dark minimal developer', color: 'bg-neutral-950', file: 'portfolio.html' },
  { id: 'prism', name: 'Prism SaaS', desc: 'Clean light SaaS landing', color: 'bg-white', file: 'prism-saas.html' },
  { id: 'sakura', name: 'Sakura Enterprise', desc: 'Dark enterprise AI electric blue', color: 'bg-neutral-950', file: 'sakura-saas.html' },
  { id: 'vantage', name: 'VANTAGE Protocol', desc: 'Neon acid yellow cyberpunk', color: 'bg-black', file: 'vantage.html' },
  { id: 'littlebee', name: 'LittleBee Trading', desc: 'Premium dark fintech dashboard', color: 'bg-neutral-950', file: 'LITTLEBEE.html' },
  { id: 'workflows', name: 'Workflows Manager', desc: 'Light sage team management', color: 'bg-emerald-50', file: 'Workflows.html' },
  { id: 'crextio', name: 'Crextio HR', desc: 'Warm cream HR platform', color: 'bg-amber-50', file: 'crextio.html' },
  { id: 'flux', name: 'Flux Health', desc: 'Clean health monitoring dashboard', color: 'bg-slate-100', file: 'flux.html' },
  { id: 'vistore-smarter-crm-stronger-sales', name: 'Vistore - Smarter CRM, Stronger Sales', desc: 'Light glassmorphism purple-accented dashboard', color: 'bg-white', file: 'Vistore---Smarter-CRM-Stronger-Sales.html' },


];
